export const LUNAR_PHASES = {
  NEW: "NEW",
  FIRST_QUARTER: "FIRST_QUARTER",
  FULL: "FULL",
  LAST_QUARTER: "LAST_QUARTER",
};

export const SYNODIC_MONTH_IN_MS = 29.53058868 * 24 * 60 * 60 * 1000;
